### ISSUE TITLE
Replace stormpath authentication with basic Spring Auth.  

### ISSUE THREAD

**Issue by bordercases** [STARInformatics/tkbio#5]
As an open source application we'll be getting a larger array of contributors. Without issuing the applications individually through contacting us, or having a single accessible "standard account" the application won't start. Since neither are desirable we should remove the necessity for Stormpath at least for now.

**Comment by cmungall** [comment]
+1

**Comment by goodb** [comment]
Yes.  Remove the third-party dependency here.

**Comment by goodb** [comment]
Most likely meaning use the Spring authentication system.

**Comment by goodb** [comment]
moved to https://github.com/NCATS-Tangerine/tkbio/issues/2
