### ISSUE TITLE
re-organize code repository: knowledge beacon API, blackboard API, and user interface

### ISSUE THREAD

**Issue by goodb** [STARInformatics/tkbio#6]
I think some code repository restructuring is in order.  I suggest breaking out three repositories (1) knowledge beacon API: swagger document, generated stub code in java and in python, and an example implementation of the beacon API over either semmedDB or monarch.   (2) the blackboard API (perhaps could be called knowledge beacon network API to continue following the ga4gh system).  This would contain the controller for accessing multiple beacons at once.  Its the API that any client (ours or the sort of thing NCATS developers are building with python notebooks, cytoscape and neo4j) would be talking to.  and (3) the human interface for accessing this data - the knowledge.bio front end.  (kb4).

**Comment by goodb** [comment]
Looking for comments here.  I think this is important.

**Comment by goodb** [comment]
![screen shot 2017-04-27 at 12 28 21 pm](https://cloud.githubusercontent.com/assets/2086122/25500795/378db888-2b45-11e7-9e7f-049fe60ec1e6.png)

This is what I am thinking here.

**Comment by goodb** [comment]
knowledge beacon API isolated and moved out to:
https://github.com/STARInformatics/translator-knowledge-beacon

**Comment by goodb** [comment]
Adding a 4th repository to the list - keeping the reference Beacon implementation separate in its own repository.  When finished we will have repos, all of which will eventually move over under the NCATS Translator umbrella: 

1. The **Knowledge Beacon API** definition.  https://github.com/STARInformatics/translator-knowledge-beacon .This will hold the YAML swagger document and documentation for generating server stubs and clients and code (and/or good documentation) for testing. 
2. The **Reference Beacon**.  This will hold the code for fully functional implementation of a Beacon that is kept in step with the latest changes of Beacon API Spec.  This will initially be populated by the "kb3" content extracted from SemmedDB and mapped to Wikidata.  
3. The **TKBIO user interface** https://github.com/STARInformatics/tkbio/ .  This is the code that runs the knowledge.bio web application that is driven by the Beacon network.  
4. The **Beacon Aggregator**  This code will provide a Web service that operates over the Beacon network to provide a single software interface over the all the Beacons.  This should eventually be used to drive the TKBIO user interface.

**Comment by goodb** [comment]
4 repos are now extracted and forked over to https://github.com/NCATS-Tangerine including:
https://github.com/NCATS-Tangerine/reference-beacon and
https://github.com/NCATS-Tangerine/beacon-aggregator

**Comment by cmungall** [comment]
Did you mean to do a fork rather than transfer the repo? It probably doesn't make much difference but it leaves open possible confusion about the 'true' fork. Close again if this not a concern.

**Comment by cmungall** [comment]
OK, this way is best as we can transfer individual tickets
